version: '3'
services:
  web:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
  api:
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app

  mysql:
    image: mysql:8.0.30
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
